default_install_hook_types = ["pre-commit", "pre-push"]
fail_fast = false

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v5.0.0"
hooks = [
    { id = "no-commit-to-branch", args = ["--branch", "main"], stages = ["pre-commit"], priority = 0 },
    { id = "end-of-file-fixer", stages = ["pre-commit"], priority = 10 },
    { id = "trailing-whitespace", stages = ["pre-commit"], priority = 11 },
    { id = "check-ast", stages = ["pre-commit", "pre-push"], priority = 20 },
    { id = "check-added-large-files", args = ["--maxkb=4096"], stages = ["pre-commit", "pre-push"], priority = 20 },
    { id = "detect-private-key", stages = ["pre-commit", "pre-push"], priority = 20 },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.8.0"
hooks = [
    { id = "ruff-check", stages = ["pre-commit"], priority = 20 },
    { id = "ruff-format", args = ["--check"], stages = ["pre-commit"], priority = 20 },
]

[[repos]]
repo = "https://github.com/sirwart/ripsecrets"
rev = "v0.1.11"
hooks = [
    { id = "ripsecrets", args = ["--strict-ignore"], require_serial = true, stages = ["pre-commit", "pre-push"], priority = 20 },
]

[[repos]]
repo = "local"
hooks = [
    { id = "shellcheck", entry = "shellcheck", language = "system", types = ["shell"], stages = ["pre-commit"], priority = 20 },
]
